### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Kasualix** [MCUpdater/RandomWorldName#2]
please make ["Generate Name"](https://github.com/MCUpdater-Mods/RandomWorldName/blob/42b3a366f793b1e31300d3fdbe672c1e35a6a471/src/main/java/com/mcupdater/randomworldname/RandomWorldName.java#L34) localizable.

**Comment by smbarbour** [comment]
Done via https://github.com/MCUpdater-Mods/RandomWorldName/commit/82e10fc29ee3dd591692b911b340132cfd6caa88
